### ISSUE TITLE
Updates for 4.0 after 4.0.0rc1 

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1339]
Starting a list, checking it twice...

- [x] update release docs to specify more better conda install https://github.com/dib-lab/sourmash/issues/1337
- [x] figure out setuptools_scm stuff https://github.com/dib-lab/sourmash/issues/1337
- [x] document `sourmash sketch` behavior on streaming per https://github.com/dib-lab/sourmash/issues/1315#issuecomment-780906376; provide example

**Comment by ctb** [comment]
- [x] re-examine release notes and confirm that no numerical changes are expected in output from v3.5.x; add reassurance to that effect

**Comment by ctb** [comment]
- [x] fix selection of genomes in command-line usage demo so that the compare plot is actually useful

**Comment by ctb** [comment]
- [x] merge #1347 and document updates in release notes

**Comment by ctb** [comment]
- [x] add note re compatibility of databases per https://github.com/dib-lab/sourmash/issues/1356
