### ISSUE TITLE
roadmap thoughts for 4.1 and 4.2

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1481]
A list of the big features I'm thinking about for sourmash v4.1 and v4.2 -- please edit, amend, and append with your own as you have them. I'd like to keep a clear picture of _necessary_ features as separate from "would be nice" :)

# 4.1

definitely:

- [x] prefetch functionality in #1370
- [x] updated databases for GTDB, NCBI based on ZipFile, for use with prefetch/greyhound

# 4.2 

- [ ] separation of LCA Databases into revindex and taxonomy https://github.com/dib-lab/sourmash/issues/969
- [ ] a way to override taxonomy information with updated taxonomy

cc @luizirber @bluegenes @taylorreiter

**Comment by ctb** [comment]
well, we kinda got there 😆 ref https://github.com/sourmash-bio/sourmash/issues/1604

**Comment by ctb** [comment]
no longer relevant, I guess. we don't really do roadmaps it seems :)
