### ISSUE TITLE
release v4.6.1 - draft release notes & release checklist

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2392]
## release checklist

Release candidate testing:
- [x] Command line tests pass for a release candidate
- [x] All eight release candidate wheels are built

Releasing to PyPI:

- [x] RC tag(s)s deleted on github
- [x] Release tag cut
- [x] Release notes written
- [x] All eight release wheels built
- [x] Release wheels uploaded to pypi
- [x] tar.gz distribution uploaded to pypi

After release to PyPI and conda-forge/bioconda packages built:

- [x] [PyPI page](https://pypi.org/project/sourmash/) updated
- [x] Zenodo DOI successfully minted upon new github release - [see search results](https://zenodo.org/search?page=1&size=20&q=sourmash)
- [x] `pip install sourmash` installs the correct version
- [x] `mamba create -n smash-release -y sourmash` installs the correct version

**Comment by ctb** [comment]
## release notes

This is a quick patch-fix for sourmash v4.6.0, which introduced bug https://github.com/sourmash-bio/sourmash/issues/2390. This bug broke `sourmash sketch ... -o <file>` with multiple ksizes, so that `.zip` and `.sqldb` output files contained only one ksize.

Bug fixes:
- fix `sourmash sketch ... -o <file>.zip` bug introduced in #2329 and released in v4.6.0 (#2391)
- disable cibuildwheel on PRs again (#2389)

**Comment by ctb** [comment]
conda-forge: https://github.com/conda-forge/sourmash-minimal-feedstock/pull/39

**Comment by ctb** [comment]
bioconda: https://github.com/bioconda/bioconda-recipes/pull/38223

**Comment by ctb** [comment]
🎉 ✨
