### ISSUE TITLE
sourmash v4.8.3 release - checklist and release notes

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2718]
Release candidate testing:
- [x] Command line tests pass for a release candidate
- [x] All eight release candidate wheels are built

Releasing to PyPI:

- [x] RC tag(s)s deleted on github
- [x] Release tag cut
- [x] Release notes written
- [x] All eight release wheels built
- [x] Release wheels uploaded to pypi
- [x] tar.gz distribution uploaded to pypi

After release to PyPI and conda-forge/bioconda packages built:

- [x] [PyPI page](https://pypi.org/project/sourmash/) updated
- [x] Zenodo DOI successfully minted upon new github release - [see search results](https://zenodo.org/search?page=1&size=20&q=sourmash&sort=mostrecent)
- [x] `pip install sourmash` installs the correct version
- [x] [conda-forge sourmash-minimal-feedstock](https://github.com/conda-forge/sourmash-minimal-feedstock) has updated `sourmash-minimal` to the correct version 
- [x] `mamba create -n smash-release -y sourmash` installs the correct version

**Comment by ctb** [comment]
## Release notes

Minor new features:

* add support for `-E/--extension` to sig split (#2712)
* add a `sourmash.cli.parse_args([...])` function (#2691)
* update plugin support for argparse usage/description/epilog (#2696)

Cleanup and documentation updates:

* add gtdb-rs214 info (#2618, #2621, #2690)
* update JOSS paper for v4 (#1361)
* fix tutorial notebook links (#2633)
* Update URL for sourmash/fig.py (#2586)
* change `matching_hashes.sig` to `matching-hashes.sig` in documentation (#2713)
* patch lineage_summary documentation (#2693)
* switch dib-lab links to sourmash-bio links in .md files (#2588)

Developer updates:

* add upload token for codecov (#2632)
* build: fix clippy lints and MSRV check (#2680)
* maturin: move deprecated definition from Cargo.toml to pyproject.toml (#2597)
* update the core documentation building packages: Sphinx, myst-parser, and docutils (#2657)
* update the dependabot config to allow automatic rebases (#2634)
* update version to 4.8.3-dev (#2584)
* Build: bump maturin to 1.x (#2650)
* Clippy beta (1.70) fix (#2596)
* Fix clippy lint introduced in 1.71 beta (#2630)
* fix release procedure based on v4.8.0 release (#2551)
* Update docutils requirement from <0.20,>=0.17.1 to >=0.17.1,<0.21 (#2611)
* Update pytest requirement from <7.4.0,>=6.2.4 to >=6.2.4,<7.5.0 (#2659)
* Fix: update a manifest test to use temp directory (#2689)

Dependabot updates:

* Bump cachix/install-nix-action from 20 to 21 (#2625)
* Bump cachix/install-nix-action from 21 to 22 (#2651)
* Bump chrono from 0.4.24 to 0.4.25 (#2628)
* Bump chrono from 0.4.25 to 0.4.26 (#2636)
* Bump criterion from 0.3.6 to 0.5.1 (#2629)
* Bump getrandom from 0.2.9 to 0.2.10 (#2645)
* Bump log from 0.4.17 to 0.4.18 (#2623)
* Bump log from 0.4.18 to 0.4.19 (#2641)
* Bump log from 0.4.19 to 0.4.20 (#2715)
* Bump memmap2 from 0.5.10 to 0.6.1 (#2613)
* Bump memmap2 from 0.6.1 to 0.6.2 (#2626)
* Bump memmap2 from 0.6.2 to 0.7.0 (#2643)
* Bump memmap2 from 0.7.0 to 0.7.1 (#2658)
* Bump once_cell from 1.17.1 to 1.17.2 (#2622)
* Bump once_cell from 1.17.2 to 1.18.0 (#2635)
* Bump ouroboros from 0.15.6 to 0.17.0 (#2654)
* Bump ouroboros from 0.17.0 to 0.17.2 (#2687)
* Bump proptest from 1.1.0 to 1.2.0 (#2627)
* Bump pypa/cibuildwheel from 2.12.1 to 2.12.3 (#2590)
* Bump pypa/cibuildwheel from 2.12.3 to 2.13.0 (#2624)
* Bump pypa/cibuildwheel from 2.13.0 to 2.13.1 (#2642)
* Bump pypa/cibuildwheel from 2.13.1 to 2.14.0 (#2673)
* Bump pypa/cibuildwheel from 2.14.0 to 2.14.1 (#2681)
* Bump pypa/cibuildwheel from 2.14.1 to 2.15.0 (#2716)
* Bump serde from 1.0.160 to 1.0.162 (#2609)
* Bump serde from 1.0.162 to 1.0.163 (#2612)
* Bump serde from 1.0.163 to 1.0.164 (#2644)
* Bump serde from 1.0.164 to 1.0.166 (#2666)
* Bump serde from 1.0.166 to 1.0.168 (#2679)
* Bump serde_json from 1.0.100 to 1.0.103 (#2682)
* Bump serde_json from 1.0.103 to 1.0.104 (#2701)
* Bump serde_json from 1.0.96 to 1.0.97 (#2653)
* Bump serde_json from 1.0.97 to 1.0.99 (#2660)
* Bump serde_json from 1.0.99 to 1.0.100 (#2675)
* Bump supercharge/redis-github-action from 1.5.0 to 1.6.0 (#2700)
* Bump tempfile from 3.5.0 to 3.6.0 (#2639)
* Bump tempfile from 3.6.0 to 3.7.0 (#2686)
* Bump tempfile from 3.7.0 to 3.7.1 (#2705)
* Bump thiserror from 1.0.40 to 1.0.43 (#2674)
* Bump thiserror from 1.0.43 to 1.0.44 (#2685)
* Bump wasm-bindgen from 0.2.84 to 0.2.86 (#2615)
* Bump wasm-bindgen from 0.2.86 to 0.2.87 (#2640)
* Bump wasm-bindgen-test from 0.3.34 to 0.3.36 (#2620)
* Bump wasm-bindgen-test from 0.3.36 to 0.3.37 (#2656)
* Bump web-sys from 0.3.61 to 0.3.63 (#2619)
* Bump web-sys from 0.3.63 to 0.3.64 (#2655)

**Comment by ctb** [comment]
note from testenv2 run: we get,
>DEPRECATION: git+https://github.com/sourmash-bio/sourmash.git@release/v4.8.3#egg
=sourmash[test] contains an egg fragment with a non-PEP 508 name pip 25.0 will enforce this behaviour change. A possible replacement is to use the req @ url syntax, and remove the egg fragment. Discussion can be found at https://github.com/pypa/pip/issues/11617

**Comment by ctb** [comment]
note also:
>an unsupported platform tag emscripten ...
blocks upload to pypi, per #2553. So I delete that wheel before using twine to upload wheels.

**Comment by ctb** [comment]
bioconda PR: https://github.com/bioconda/bioconda-recipes/pull/42538

**Comment by ctb** [comment]
conda-forge PR: https://github.com/conda-forge/sourmash-minimal-feedstock/pull/51

**Comment by ctb** [comment]
https://github.com/sourmash-bio/sourmash/releases/tag/v4.8.3 🎉

**Comment by luizirber** [comment]
pyodide PR: https://github.com/pyodide/pyodide/pull/4075
nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/230596

**Comment by ctb** [comment]
@luizirber should I add pyodide & nixpkgs to release checklist?

**Comment by luizirber** [comment]
> @luizirber should I add pyodide & nixpkgs to release checklist?

I'm a maintainer for the nixpkgs package, and it should auto-create a PR when a new version is available (🤞 ). So, good as informational, but will mostly automerge?

for pyodide it is manual, so yes, probably good to be in the release checklist
