### ISSUE TITLE
release checklist for sourmash v4.8.6 

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2991]
Release candidate testing:
- [x] Command line tests pass for a release candidate
- [x] All eight release candidate wheels are built

Releasing to PyPI:

- [x] RC tag(s)s deleted on github
- [x] Release tag cut
- [x] Release notes written
- [x] All eight release wheels built
- [x] Release wheels uploaded to pypi
- [x] tar.gz distribution uploaded to pypi

After release to PyPI and conda-forge/bioconda packages built:

- [x] [PyPI page](https://pypi.org/project/sourmash/) updated
- [ ] Zenodo DOI successfully minted upon new github release - [see search results](https://zenodo.org/search?page=1&size=20&q=sourmash&sort=mostrecent)
- [x] `pip install sourmash` installs the correct version
- [x] [conda-forge sourmash-minimal-feedstock](https://github.com/conda-forge/sourmash-minimal-feedstock) has updated `sourmash-minimal` to the correct version 
- [x] `mamba create -n smash-release -y sourmash` installs the correct version

Optional but recommended:

- [ ] PR submitted to update pyodide version
- [ ] PR submitted to update spack version

**Comment by ctb** [comment]
had to re-enable the zenodo integration after I noticed that v4.8.6 didn't update. not sure I should bother uploading v4.8.6 to zenodo since last version is on there and presumably next version will Just Work.
